[project]
id = "mikespub/heroku-python-sample"
name = "Heroku Python App using Buildpacks"
version = "0.1.0"

[build]
exclude = [
	".git",
	".github",
	"*.pyc",
	"*.pyo",
	"*.pyd",
	"__pycache__",
	".pytest_cache",
	"*.yml",
	".cnab",
	"venv",
	"*.droplet",
	"*.cache"
]

[[build.buildpacks]]
uri = "heroku/python"

